version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "k8s.io/api"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "k8s.io/apimachinery"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "k8s.io/client-go"
        update-types: [ "version-update:semver-patch" ]