version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      main:
        applies-to: version-updates
        patterns:
          - '*'
      sec:
        applies-to: security-updates
        patterns:
          - '*'
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: k8s.io/api
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: k8s.io/apimachinery
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: k8s.io/client-go
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
      - dependency-name: sigs.k8s.io/controller-runtime
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    groups:
      main:
        applies-to: version-updates
        patterns:
          - '*'
      sec:
        applies-to: security-updates
        patterns:
          - '*'
