# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - golint
      text: "underscore"

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet
    - goimports
    - gomnd

run:
  timeout: 10m
  skip-files:
    - api/v1alpha1/zz_generated.deepcopy.go