issues:
  exclude-dirs:
    - hack
  exclude-files:
    - api/v1alpha1/zz_generated.deepcopy.go
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - golint
      text: underscore
    - linters:
        - gomnd
      text: "mnd: Magic number: 0o644"

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gofumpt
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - vet
    - goimports
    - gomnd

run:
  timeout: 10m
