
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-operator-aiven-io-v1alpha1-connectionpool
  failurePolicy: Fail
  name: mconnectionpool.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - connectionpools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-operator-aiven-io-v1alpha1-database
  failurePolicy: Fail
  name: mdatabase.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-operator-aiven-io-v1alpha1-pg
  failurePolicy: Fail
  name: mpg.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pgs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-operator-aiven-io-v1alpha1-project
  failurePolicy: Fail
  name: mproject.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - projects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k8s-operator-aiven-io-v1alpha1-serviceuser
  failurePolicy: Fail
  name: mserviceuser.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceusers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-operator-aiven-io-v1alpha1-connectionpool
  failurePolicy: Fail
  name: vconnectionpool.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - connectionpools
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-operator-aiven-io-v1alpha1-database
  failurePolicy: Fail
  name: vdatabase.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-operator-aiven-io-v1alpha1-pg
  failurePolicy: Fail
  name: vpg.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pgs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-operator-aiven-io-v1alpha1-project
  failurePolicy: Fail
  name: vproject.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - projects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-k8s-operator-aiven-io-v1alpha1-serviceuser
  failurePolicy: Fail
  name: vserviceuser.kb.io
  rules:
  - apiGroups:
    - k8s-operator.aiven.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceusers
  sideEffects: None
