# permissions for end users to edit cassandras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandra-editor-role
rules:
- apiGroups:
  - aiven.io
  resources:
  - cassandras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiven.io
  resources:
  - cassandras/status
  verbs:
  - get
