# permissions for end users to view clickhouses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-viewer-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - clickhouses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - clickhouses/status
    verbs:
      - get
