# permissions for end users to edit clickhouseusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouseuser-editor-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseusers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseusers/status
    verbs:
      - get
