# permissions for end users to view clickhouseroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clickhouserole-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aiven-operator
    app.kubernetes.io/part-of: aiven-operator
    app.kubernetes.io/managed-by: kustomize
  name: clickhouserole-viewer-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseroles
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - clickhouseroles/status
    verbs:
      - get
