# permissions for end users to view connectionpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionpool-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - connectionpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - connectionpools/status
  verbs:
  - get
