# permissions for end users to edit connectionpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connectionpool-editor-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - connectionpools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - connectionpools/status
    verbs:
      - get
