# permissions for end users to edit kafkaschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaschema-editor-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas/status
  verbs:
  - get
