# permissions for end users to view kafkaacls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaacl-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaacls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaacls/status
  verbs:
  - get
