# permissions for end users to view kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkatopic-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkatopics/status
  verbs:
  - get
