# permissions for end users to view kafkaschemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaschema-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas/status
  verbs:
  - get
