# permissions for end users to edit kafkaconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaconnector-editor-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnectors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - kafkaconnectors/status
    verbs:
      - get
