# permissions for end users to edit mysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-editor-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - mysqls
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - mysqls/status
    verbs:
      - get
