---
# permissions for end users to view opensearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: opensearch-viewer-role

rules:
  - apiGroups: [aiven.io]
    resources: [opensearches]
    verbs: [get, list, watch]
  - apiGroups: [aiven.io]
    resources: [opensearches/status]
    verbs: [get]
