# permissions for end users to edit pgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pg-editor-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - pgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - pgs/status
  verbs:
  - get
