# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresql-viewer-role
rules:
  - apiGroups:
      - aiven.io
    resources:
      - postgresqls
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - aiven.io
    resources:
      - postgresqls/status
    verbs:
      - get
