
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - connectionpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - connectionpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaacls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaacls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaconnects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaconnects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkaschemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - pgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - pgs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - projectvpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - projectvpcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceintegrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceusers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceusers/status
  verbs:
  - get
