# permissions for end users to view serviceusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceuser-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceusers/status
  verbs:
  - get
