# permissions for end users to view serviceintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceintegration-viewer-role
rules:
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceintegrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s-operator.aiven.io
  resources:
  - serviceintegrations/status
  verbs:
  - get
