---
# permissions for end users to view serviceintegrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: serviceintegration-viewer-role

rules:
  - apiGroups: [aiven.io]
    resources: [serviceintegrations]
    verbs: [get, list, watch]
  - apiGroups: [aiven.io]
    resources: [serviceintegrations/status]
    verbs: [get]
