# permissions for end users to edit serviceusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceuser-editor-role
rules:
- apiGroups:
  - aiven.io
  resources:
  - serviceusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aiven.io
  resources:
  - serviceusers/status
  verbs:
  - get
