apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: aiven-k8s-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ConnectionPool is the Schema for the connectionpools API
      displayName: Connection Pool
      kind: ConnectionPool
      name: connectionpools.k8s-operator.aiven.io
      version: v1alpha1
    - description: Database is the Schema for the databases API
      displayName: Database
      kind: Database
      name: databases.k8s-operator.aiven.io
      version: v1alpha1
    - description: Project is the Schema for the projects API
      displayName: Project
      kind: Project
      name: projects.k8s-operator.aiven.io
      version: v1alpha1
    - description: ProjectVPC is the Schema for the projectvpcs API
      displayName: Project VPC
      kind: ProjectVPC
      name: projectvpcs.k8s-operator.aiven.io
      version: v1alpha1
  description: A Kubernetes operator for provisioning and managing Aiven Databases and other resources
  displayName: Aiven Kubernetes Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aiven
  - cloud
  links:
  - name: Aiven K8s Operator
    url: https://aiven-k8s-operator.domain
  maintainers:
  - email: ivan.savciuc@gmail.com
    name: Ivan Savciuc
  maturity: alpha
  provider:
    name: as Custom Resources in your cluster.aiven-operator
  version: 0.0.0
