apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: valkey-sample
    app.kubernetes.io/part-of: aiven-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aiven-operator
  name: valkey-sample
spec:
  # TODO(user): Add fields here
