apiVersion: aiven.io/v1alpha1
kind: Clickhouse
metadata:
  name: ch-sample
spec:
  authSecretRef:
    name: aiven-token
    key: token

  connInfoSecretTarget:
    name: os-secret

  project: my-project

  cloudName: google-europe-west1
  plan: startup-4

  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00
