apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  name: redis-sample
spec:
  authSecretRef:
    name: aiven-token
    key: token

  connInfoSecretTarget:
    name: redis-token

  project: my-project

  cloudName: google-europe-west1
  plan: startup-2

  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00

  userConfig:
    redis_maxmemory_policy: allkeys-random
