apiVersion: aiven.io/v1alpha1
kind: KafkaTopic
metadata:
  name: kafkatopic-sample
spec:
  serviceName: kafka-sample
  project: dev-sandbox
  partitions: 3
  replication: 2
  tags:
    - key: tagk1,
      value: tagv1
    - key: tagk2,
      value: tagv2
  config:
    flush_ms: 100
