apiVersion: aiven.io/v1alpha1
kind: KafkaConnect
metadata:
  name: kafkaconnect-sample
spec:
  project: dev-sandbox
  cloudName: google-europe-west1
  plan: startup-4
  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00
