apiVersion: aiven.io/v1alpha1
kind: Kafka
metadata:
  name: kafka-sample
spec:
  project: dev-sandbox
  cloudName: google-europe-west1
  plan: business-4
  maintenanceWindowDow: friday
  maintenanceWindowTime: 23:00:00
  kafkaUserConfig:
    kafka_version: '2.4'
