## Append samples you want in your CSV to this file as resources ##
resources:
- aiven.io_v1alpha1_redis.yaml
- aiven.io_v1alpha1_opensearch.yaml
- aiven.io_v1alpha1_clickhouse.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
