# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/aiven.io_clickhouses.yaml
- bases/aiven.io_clickhouseusers.yaml
- bases/aiven.io_connectionpools.yaml
- bases/aiven.io_databases.yaml
- bases/aiven.io_kafkas.yaml
- bases/aiven.io_kafkaacls.yaml
- bases/aiven.io_kafkaconnects.yaml
- bases/aiven.io_kafkaconnectors.yaml
- bases/aiven.io_kafkaschemas.yaml
- bases/aiven.io_kafkatopics.yaml
- bases/aiven.io_opensearches.yaml
- bases/aiven.io_postgresqls.yaml
- bases/aiven.io_projects.yaml
- bases/aiven.io_projectvpcs.yaml
- bases/aiven.io_redis.yaml
- bases/aiven.io_serviceintegrations.yaml
- bases/aiven.io_serviceusers.yaml
- bases/aiven.io_mysqls.yaml
- bases/aiven.io_cassandras.yaml
- bases/aiven.io_grafanas.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_clickhouses.yaml
- patches/webhook_in_clickhouseusers.yaml
- patches/webhook_in_connectionpools.yaml
- patches/webhook_in_databases.yaml
- patches/webhook_in_kafkas.yaml
- patches/webhook_in_kafkaacls.yaml
- patches/webhook_in_kafkaconnects.yaml
- patches/webhook_in_kafkaconnectors.yaml
- patches/webhook_in_kafkaschemas.yaml
- patches/webhook_in_kafkatopics.yaml
- patches/webhook_in_opensearches.yaml
- patches/webhook_in_postgresqls.yaml
- patches/webhook_in_projects.yaml
- patches/webhook_in_redis.yaml
- patches/webhook_in_serviceintegrations.yaml
- patches/webhook_in_serviceusers.yaml
- patches/webhook_in_mysqls.yaml
- patches/webhook_in_cassandras.yaml
- patches/webhook_in_grafanas.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_clickhouses.yaml
- patches/cainjection_in_clickhouseusers.yaml
- patches/cainjection_in_connectionpools.yaml
- patches/cainjection_in_databases.yaml
- patches/cainjection_in_kafkas.yaml
- patches/cainjection_in_kafkaacls.yaml
- patches/cainjection_in_kafkaconnects.yaml
- patches/cainjection_in_kafkaconnectors.yaml
- patches/cainjection_in_kafkaschemas.yaml
- patches/cainjection_in_kafkatopics.yaml
- patches/cainjection_in_opensearches.yaml
- patches/cainjection_in_postgresqls.yaml
- patches/cainjection_in_projects.yaml
- patches/cainjection_in_redis.yaml
- patches/cainjection_in_serviceintegrations.yaml
- patches/cainjection_in_serviceusers.yaml
- patches/cainjection_in_mysqls.yaml
- patches/cainjection_in_cassandras.yaml
- patches/cainjection_in_grafanas.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
