---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration

metadata:
  name: my-service-integration

spec:
  authSecretRef:
    name: aiven-token
    key: token

  project: aiven-project-name

  integrationType: kafka_logs
  sourceServiceName: my-source-service-name
  destinationServiceName: my-destination-service-name

  kafkaLogs:
    kafka_topic: my-kafka-topic
