# yaml-language-server: $schema=https://squidfunk.github.io/mkdocas-material/schema.json
site_name: Aiven Operator
copyright: Aiven Team
repo_url: https://github.com/aiven/aiven-operator/
edit_uri: blob/main/docs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details
plugins:
  - search
  - offline
theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: red
      accent: deep-orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep-orange
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Installation:
      - installation/prerequisites.md
      - installation/helm.md
      - installation/kubectl.md
      - installation/uninstalling.md
  - authentication.md
  - Resources:
      - resources/project.md
      - resources/project-vpc.md
      - Kafka:
        - resources/kafka/index.md
        - resources/kafka/schema.md
        - resources/kafka/connect.md
      - resources/postgresql.md
      - resources/opensearch.md
      - resources/redis.md
      - resources/service-integrations.md
  - troubleshooting.md
  - Contributing:
      - contributing/index.md
      - contributing/developer-guide.md
  - api-reference.md
