name: tests

on:
  pull_request:
    branches: [main]

jobs:

  acceptance_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Run acceptance tests
        run: make test-acc
        env:
          AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
          AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }}
