name: generate files

on:
  pull_request: {}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: generate files
        run: make generate
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(userconfigs): generate files"
