name: pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release_pages:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --prefix ./docs
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - run: make generate-docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
