name: scorecard tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  scorecard-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.2.0

      - name: Install Operator SDK
        run:
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.9.1/operator-sdk_linux_amd64 &&
          chmod +x operator-sdk_linux_amd64 &&
          sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

      - name: Run scorecard tests
        run: make test-scorecard
